GET http://localhost:2000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkV5c2hhMTIzNDU2IiwicGFzc3dvcmQiOiIkMmIkMTAkNTAzWUhNamNGVEtOVUdwaS85N0ltZXJpOFYxeC45MjBMSFRsbW4ub3FJejZOTnJ0c3p2WWkiLCJpYXQiOjE3NDU2MDY1MDcsImV4cCI6MTc0NTYwNjUyMn0.0rXsl1WIdvLWmvTFG75ThFqNl2DGKFJdFWO5I_UNoV0

###
DELETE http://localhost:1000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkV5c2hhMTIzNDU2IiwicGFzc3dvcmQiOiIkMmIkMTAkLzQuMnRTWnlYbWtYNnM5MWNKd3U1T2xsVWpBcTZmUXROYzRuT25CbUl5L0xJdVBJb1RHTUMiLCJpYXQiOjE3NDU2MDY4MzAsImV4cCI6MTc0NTYwNjg1MH0.WvSQTIaZMEqMHenMQx_V9CsvPJN0ywXZH0gomANhDw8"
}

###
POST http://localhost:1000/signup
Content-Type: application/json

{
    "username": "Eysha1234567",
    "password": "123456"
}
###
POST  http://localhost:1000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkV5c2hhMTIzNDU2NyIsInBhc3N3b3JkIjoiJDJiJDEwJFVIb0tlSFNuL0o2Vm5UNUhudE5kak85aDUvSnlDSTY3Qmt1RVB3SXhxdUgzelVGa1pITkJLIiwiaWF0IjoxNzQ1NjA2ODcxLCJleHAiOjE3NDU2MDY4OTF9.-mdKJSJRVlccoXnDJ6Hu18yiIBCWS4Y2G0VWKJTgnYI"
}


###
POST http://localhost:1000/login
Content-Type: application/json


    {"username": "Ey", "password": "123456"}
